import {
  ambulance_ambulance_type, ambulance_ambulance_status } from "@prisma/client";

export const ambulances = [
  {
    ambulance_id: 1,
    plate_no: "QCF1027",
    ambulance_type: ambulance_ambulance_type.type_1,
    ambulance_status: ambulance_ambulance_status.available,
    hospital_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    ambulance_id: 2,
    plate_no: "QCG5831",
    ambulance_type: ambulance_ambulance_type.type_1,
    ambulance_status: ambulance_ambulance_status.on_trip,
    hospital_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    ambulance_id: 3,
    plate_no: "QCT2146",
    ambulance_type: ambulance_ambulance_type.type_2,
    ambulance_status: ambulance_ambulance_status.available,
    hospital_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    ambulance_id: 4,
    plate_no: "QCM7963",
    ambulance_type: ambulance_ambulance_type.type_2,
    ambulance_status: ambulance_ambulance_status.on_trip,
    hospital_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    ambulance_id: 5,
    plate_no: "MNL4018",
    ambulance_type: ambulance_ambulance_type.type_1,
    ambulance_status: ambulance_ambulance_status.available,
    hospital_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    ambulance_id: 6,
    plate_no: "MNK7284",
    ambulance_type: ambulance_ambulance_type.type_1,
    ambulance_status: ambulance_ambulance_status.on_trip,
    hospital_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    ambulance_id: 7,
    plate_no: "MNB6592",
    ambulance_type: ambulance_ambulance_type.type_2,
    ambulance_status: ambulance_ambulance_status.available,
    hospital_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    ambulance_id: 8,
    plate_no: "MNT8325",
    ambulance_type: ambulance_ambulance_type.type_2,
    ambulance_status: ambulance_ambulance_status.on_trip,
    hospital_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    ambulance_id: 9,
    plate_no: "MTL3057",
    ambulance_type: ambulance_ambulance_type.type_1,
    ambulance_status: ambulance_ambulance_status.available,
    hospital_id: 3,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    ambulance_id: 10,
    plate_no: "MTN9471",
    ambulance_type: ambulance_ambulance_type.type_1,
    ambulance_status: ambulance_ambulance_status.on_trip,
    hospital_id: 3,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    ambulance_id: 11,
    plate_no: "MTR4168",
    ambulance_type: ambulance_ambulance_type.type_2,
    ambulance_status: ambulance_ambulance_status.available,
    hospital_id: 3,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    ambulance_id: 12,
    plate_no: "MTA5639",
    ambulance_type: ambulance_ambulance_type.type_2,
    ambulance_status: ambulance_ambulance_status.on_trip,
    hospital_id: 3,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
];
