import { patient_medical_condition, patient_priority_level } from "@prisma/client";

export const patients = [
  {
    patient_id: 1,
    name: "Miguel Tan",
    age: 58,
    medical_condition: patient_medical_condition.cardiac,
    priority_level: patient_priority_level.critical,
    contact_person: "Liza Tan",
    contact_number: "09171234567",
    transfer_status: null,
    ref_location_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 2,
    name: "Andrea Cruz",
    age: 34,
    medical_condition: patient_medical_condition.trauma,
    priority_level: patient_priority_level.moderate,
    contact_person: "Jose Cruz",
    contact_number: "09172345678",
    transfer_status: null,
    ref_location_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 3,
    name: "Ramon Santos",
    age: 67,
    medical_condition: patient_medical_condition.respiratory,
    priority_level: patient_priority_level.critical,
    contact_person: "Maria Santos",
    contact_number: "09173456789",
    transfer_status: null,
    ref_location_id: 3,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 4,
    name: "Carla Villanueva",
    age: 45,
    medical_condition: patient_medical_condition.neurological,
    priority_level: patient_priority_level.moderate,
    contact_person: "Rosa Villanueva",
    contact_number: "09174567890",
    transfer_status: null,
    ref_location_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 5,
    name: "Mark Delgado",
    age: 29,
    medical_condition: patient_medical_condition.other,
    priority_level: patient_priority_level.routine,
    contact_person: "Enrique Salazar",
    contact_number: "09175678901",
    transfer_status: null,
    ref_location_id: 5,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 6,
    name: "John Dela Rosa",
    age: 72,
    medical_condition: patient_medical_condition.cardiac,
    priority_level: patient_priority_level.critical,
    contact_person: "Ana Dela Rosa",
    contact_number: "09176789012",
    transfer_status: null,
    ref_location_id: 6,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 7,
    name: "Teresa Gomez",
    age: 50,
    medical_condition: patient_medical_condition.trauma,
    priority_level: patient_priority_level.moderate,
    contact_person: "Carlos Gomez",
    contact_number: "09177890123",
    transfer_status: null,
    ref_location_id: 7,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 8,
    name: "Victor Navarro",
    age: 38,
    medical_condition: patient_medical_condition.respiratory,
    priority_level: patient_priority_level.critical,
    contact_person: "Liza Navarro",
    contact_number: "09178901234",
    transfer_status: null,
    ref_location_id: 8,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 9,
    name: "Sofia Reyes",
    age: 61,
    medical_condition: patient_medical_condition.neurological,
    priority_level: patient_priority_level.moderate,
    contact_person: "Pedro Reyes",
    contact_number: "09179012345",
    transfer_status: null,
    ref_location_id: 9,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 10,
    name: "Daniel Mercado",
    age: 27,
    medical_condition: patient_medical_condition.other,
    priority_level: patient_priority_level.routine,
    contact_person: "Miguel Mercado",
    contact_number: "09170123456",
    transfer_status: null,
    ref_location_id: 10,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 11,
    name: "Josefa Lim",
    age: 55,
    medical_condition: patient_medical_condition.cardiac,
    priority_level: patient_priority_level.critical,
    contact_person: "Juan Lim",
    contact_number: "09171234568",
    transfer_status: null,
    ref_location_id: 11,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 12,
    name: "Renato Aquino",
    age: 43,
    medical_condition: patient_medical_condition.trauma,
    priority_level: patient_priority_level.moderate,
    contact_person: "Ana Aquino",
    contact_number: "09172345679",
    transfer_status: null,
    ref_location_id: 12,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 13,
    name: "Patricia Lopez",
    age: 36,
    medical_condition: patient_medical_condition.respiratory,
    priority_level: patient_priority_level.critical,
    contact_person: "Carlos Lopez",
    contact_number: "09173456780",
    transfer_status: null,
    ref_location_id: 13,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 14,
    name: "Ernesto Tan",
    age: 48,
    medical_condition: patient_medical_condition.neurological,
    priority_level: patient_priority_level.moderate,
    contact_person: "Maria Tan",
    contact_number: "09174567891",
    transfer_status: null,
    ref_location_id: 14,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
  {
    patient_id: 15,
    name: "Kristine dela Cruz",
    age: 25,
    medical_condition: patient_medical_condition.other,
    priority_level: patient_priority_level.routine,
    contact_person: "Pedro Cruz",
    contact_number: "09175678902",
    transfer_status: null,
    ref_location_id: 15,
    created_at: new Date(),
    updated_at: new Date(),
    is_deleted: false,
  },
];
