import { reference_location_city } from "@prisma/client";

export const reference_locations = [
	{
		ref_location_id: 1,
		hospital_id: 1,
		city: reference_location_city.Quezon_City,
		street: "12 Kalayaan Ave",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 2,
		hospital_id: 2,
		city: reference_location_city.Manila_City,
		street: "72 España Blvd",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 3,
		hospital_id: 3,
		city: reference_location_city.Muntinlupa_City,
		street: "43 Alabang Rd",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 4,
		hospital_id: 1,
		city: reference_location_city.Quezon_City,
		street: "5 Banawe St",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 5,
		hospital_id: 2,
		city: reference_location_city.Manila_City,
		street: "20 Ortigas Ave",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 6,
		hospital_id: 2,
		city: reference_location_city.Manila_City,
		street: "18 Upper McKinley Rd",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 7,
		hospital_id: 2,
		city: reference_location_city.Manila_City,
		street: "33 Ayala Ave",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 8,
		hospital_id: 2,
		city: reference_location_city.Manila_City,
		street: "14 Roxas Blvd",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 9,
		hospital_id: 2,
		city: reference_location_city.Manila_City,
		street: "50 Taft Ave",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 10,
		hospital_id: 1,
		city: reference_location_city.Quezon_City,
		street: "22 EDSA",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 11,
		hospital_id: 2,
		city: reference_location_city.Manila_City,
		street: "11 10th Ave",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 12,
		hospital_id: 3,
		city: reference_location_city.Muntinlupa_City,
		street: "7 Alabang-Zapote Rd",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 13,
		hospital_id: 2,
		city: reference_location_city.Manila_City,
		street: "19 Boni Ave",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 14,
		hospital_id: 2,
		city: reference_location_city.Manila_City,
		street: "2 NAIA Rd",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		ref_location_id: 15,
		hospital_id: 2,
		city: reference_location_city.Manila_City,
		street: "8 BGC St",
		created_at: new Date(),
		updated_at: new Date(),
	},
];
