export const reference_locations = [
  {
    ref_location_id: 1,
    city: "Quezon",
    street: "12 Kalayaan Ave",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 2,
    city: "Manila",
    street: "72 España Blvd",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 3,
    city: "Muntinlupa",
    street: "43 Alabang Rd",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 4,
    city: "Quezon City",
    street: "5 Banawe St",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 5,
    city: "Pasig",
    street: "20 Ortigas Ave",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 6,
    city: "Taguig",
    street: "18 Upper McKinley Rd",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 7,
    city: "Makati",
    street: "33 Ayala Ave",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 8,
    city: "Pasay",
    street: "14 Roxas Blvd",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 9,
    city: "Manila",
    street: "50 Taft Ave",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 10,
    city: "Quezon City",
    street: "22 EDSA",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 11,
    city: "Caloocan",
    street: "11 10th Ave",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 12,
    city: "Las Piñas",
    street: "7 Alabang-Zapote Rd",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 13,
    city: "Mandaluyong",
    street: "19 Boni Ave",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 14,
    city: "Parañaque",
    street: "2 NAIA Rd",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    ref_location_id: 15,
    city: "Taguig",
    street: "8 BGC St",
    created_at: new Date(),
    updated_at: new Date(),
  },
];
