import {
	staff_staff_role,
	staff_shift_schedule,
	staff_staff_status,
} from "@prisma/client";

export const staffs = [
	{
		staff_id: 1,
		hospital_id: 1,
		name: "Juan Dela Cruz",
		staff_role: staff_staff_role.driver,
		license_no: "LIC-482-915",
		shift_schedule: staff_shift_schedule.morning,
		staff_status: staff_staff_status.available,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 2,
		hospital_id: 1,
		name: "Maria Santos",
		staff_role: staff_staff_role.emt,
		license_no: "LIC-736-204",
		shift_schedule: staff_shift_schedule.night,
		staff_status: staff_staff_status.in_transfer,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 3,
		hospital_id: 1,
		name: "Pedro Reyes",
		staff_role: staff_staff_role.paramedic,
		license_no: "LIC-591-807",
		shift_schedule: staff_shift_schedule.morning,
		staff_status: staff_staff_status.available,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 4,
		hospital_id: 1,
		name: "Ana Bautista",
		staff_role: staff_staff_role.driver,
		license_no: "LIC-314-629",
		shift_schedule: staff_shift_schedule.night,
		staff_status: staff_staff_status.off_duty,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 5,
		hospital_id: 1,
		name: "Carlos Mendoza",
		staff_role: staff_staff_role.emt,
		license_no: "LIC-867-053",
		shift_schedule: staff_shift_schedule.morning,
		staff_status: staff_staff_status.available,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 6,
		hospital_id: 2,
		name: "Liza Torres",
		staff_role: staff_staff_role.paramedic,
		license_no: "LIC-205-478",
		shift_schedule: staff_shift_schedule.night,
		staff_status: staff_staff_status.in_transfer,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 7,
		hospital_id: 2,
		name: "Miguel Ramirez",
		staff_role: staff_staff_role.driver,
		license_no: "LIC-938-146",
		shift_schedule: staff_shift_schedule.morning,
		staff_status: staff_staff_status.available,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 8,
		hospital_id: 2,
		name: "Rosa Villanueva",
		staff_role: staff_staff_role.emt,
		license_no: "LIC-670-392",
		shift_schedule: staff_shift_schedule.night,
		staff_status: staff_staff_status.off_duty,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 9,
		hospital_id: 2,
		name: "Enrique Salazar",
		staff_role: staff_staff_role.paramedic,
		license_no: "LIC-421-580",
		shift_schedule: staff_shift_schedule.morning,
		staff_status: staff_staff_status.available,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 10,
		hospital_id: 2,
		name: "Teresa Lopez",
		staff_role: staff_staff_role.driver,
		license_no: "LIC-753-864",
		shift_schedule: staff_shift_schedule.night,
		staff_status: staff_staff_status.available,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 11,
		hospital_id: 3,
		name: "Renato Cruz",
		staff_role: staff_staff_role.emt,
		license_no: "LIC-109-735",
		shift_schedule: staff_shift_schedule.morning,
		staff_status: staff_staff_status.in_transfer,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 12,
		hospital_id: 3,
		name: "Patricia Tan",
		staff_role: staff_staff_role.paramedic,
		license_no: "LIC-682-490",
		shift_schedule: staff_shift_schedule.night,
		staff_status: staff_staff_status.off_duty,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 13,
		hospital_id: 3,
		name: "Daniel Mercado",
		staff_role: staff_staff_role.driver,
		license_no: "LIC-547-316",
		shift_schedule: staff_shift_schedule.morning,
		staff_status: staff_staff_status.available,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 14,
		hospital_id: 3,
		name: "Kristine dela Cruz",
		staff_role: staff_staff_role.emt,
		license_no: "LIC-890-271",
		shift_schedule: staff_shift_schedule.night,
		staff_status: staff_staff_status.available,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
	{
		staff_id: 15,
		hospital_id: 3,
		name: "Josefa Lim",
		staff_role: staff_staff_role.paramedic,
		license_no: "LIC-364-958",
		shift_schedule: staff_shift_schedule.morning,
		staff_status: staff_staff_status.in_transfer,
		created_at: new Date(),
		updated_at: new Date(),
		is_deleted: false,
	},
];
