import {
	transfer_transfer_status,
	transfer_priority_level,
} from "@prisma/client";

export const transfers = [
	// Patient 1 - Miguel Tan (Cardiac, Critical) - 2 transfers
	{
		transfer_id: 1,
		patient_id: 1,
		ambulance_id: 1,
		staff_id: 1,
		hospital_id: 1,
		transferred_on: new Date("2025-11-05T08:30:00"),
		priority_level: transfer_priority_level.critical,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-05T08:30:00"),
	},
	{
		transfer_id: 2,
		patient_id: 1,
		ambulance_id: 2,
		staff_id: 3,
		hospital_id: 1,
		transferred_on: new Date("2025-11-12T14:15:00"),
		priority_level: transfer_priority_level.moderate,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-12T14:15:00"),
	},
	// Patient 2 - Andrea Cruz (Trauma, Moderate) - 1 transfer
	{
		transfer_id: 3,
		patient_id: 2,
		ambulance_id: 5,
		staff_id: 7,
		hospital_id: 2,
		transferred_on: new Date("2025-11-08T10:45:00"),
		priority_level: transfer_priority_level.moderate,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-08T10:45:00"),
	},
	// Patient 3 - Ramon Santos (Respiratory, Critical) - 3 transfers
	{
		transfer_id: 4,
		patient_id: 3,
		ambulance_id: 5,
		staff_id: 6,
		hospital_id: 2,
		transferred_on: new Date("2025-11-03T07:20:00"),
		priority_level: transfer_priority_level.critical,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-03T07:20:00"),
	},
	{
		transfer_id: 5,
		patient_id: 3,
		ambulance_id: 6,
		staff_id: 9,
		hospital_id: 2,
		transferred_on: new Date("2025-11-10T16:30:00"),
		priority_level: transfer_priority_level.critical,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-10T16:30:00"),
	},
	{
		transfer_id: 6,
		patient_id: 3,
		ambulance_id: 7,
		staff_id: 6,
		hospital_id: 2,
		transferred_on: new Date("2025-11-18T09:00:00"),
		priority_level: transfer_priority_level.moderate,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-18T09:00:00"),
	},
	// Patient 6 - John Dela Rosa (Cardiac, Critical) - 1 transfer
	{
		transfer_id: 7,
		patient_id: 6,
		ambulance_id: 9,
		staff_id: 13,
		hospital_id: 3,
		transferred_on: new Date("2025-11-15T11:45:00"),
		priority_level: transfer_priority_level.critical,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-15T11:45:00"),
	},
	// Patient 7 - Teresa Gomez (Trauma, Moderate) - 1 transfer
	{
		transfer_id: 8,
		patient_id: 7,
		ambulance_id: 10,
		staff_id: 11,
		hospital_id: 3,
		transferred_on: new Date("2025-11-07T13:20:00"),
		priority_level: transfer_priority_level.moderate,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-07T13:20:00"),
	},
	// Patient 5 - Mark Delgado (Other, Routine) - 1 transfer
	{
		transfer_id: 9,
		patient_id: 5,
		ambulance_id: 3,
		staff_id: 5,
		hospital_id: 1,
		transferred_on: new Date("2025-11-14T15:00:00"),
		priority_level: transfer_priority_level.routine,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-14T15:00:00"),
	},
	// Patient 10 - Daniel Mercado (Other, Routine) - 1 transfer
	{
		transfer_id: 10,
		patient_id: 10,
		ambulance_id: 11,
		staff_id: 15,
		hospital_id: 3,
		transferred_on: new Date("2025-11-20T10:30:00"),
		priority_level: transfer_priority_level.routine,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-20T10:30:00"),
	},
	// Patient 4 - Lisa Reyes (Neurological, Critical) - 2 transfers
	{
		transfer_id: 11,
		patient_id: 4,
		ambulance_id: 7,
		staff_id: 6,
		hospital_id: 1,
		transferred_on: new Date("2025-11-01T10:00:00"),
		priority_level: transfer_priority_level.critical,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-01T10:00:00"),
	},
	{
		transfer_id: 12,
		patient_id: 4,
		ambulance_id: 1,
		staff_id: 10,
		hospital_id: 3,
		transferred_on: new Date("2025-11-19T08:15:00"),
		priority_level: transfer_priority_level.critical,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-19T08:15:00"),
	},
	// Patient 8 - Carlos Bautista (Other, Routine) - 1 transfer
	{
		transfer_id: 13,
		patient_id: 8,
		ambulance_id: 8,
		staff_id: 4,
		hospital_id: 1,
		transferred_on: new Date("2025-11-16T16:00:00"),
		priority_level: transfer_priority_level.routine,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-16T16:00:00"),
	},
	// Patient 2 - Andrea Cruz (Trauma, Routine) - 2nd transfer
	{
		transfer_id: 14,
		patient_id: 2,
		ambulance_id: 4,
		staff_id: 2,
		hospital_id: 1,
		transferred_on: new Date("2025-11-17T13:45:00"),
		priority_level: transfer_priority_level.routine,
		transfer_status: transfer_transfer_status.transferred,
		updated_on: new Date("2025-11-17T13:45:00"),
	},
];
